apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-practice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-practice
  template:
    metadata:
      labels:
        app: kubernetes-practice
    spec:
      containers:
        - name: kubernetes-practice
          image: gyureal/kubernetes-practice:no-db
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kubernetes-practice
spec:
  type: NodePort
  selector:
    app: kubernetes-practice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
