management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8181
    # actuator 엔드포인트 (보안을 위해 변경, 만약 8080 이외에는 외부에 노출되어 있지 않다면, 포트를 바꾸는 것도 하나의 방법입다. )
    # 만약 어쩔수 없이 인터넷망에 노출된다면, 스프링 시큐리티, 필터 등으로 인가된 사용자만 접근 가능하도록 추가적인 개발이 필요하다.
  endpoint:
    shutdown:
      enabled: true # shutdown 활성화
    health:
#      show-details: always
      show-components: always # up 인지만 확인
  endpoints:
    web:
      exposure:
        include: "*" # 전체 노출

info:
  app:
    name: actuator-practice

logging:
  level:
    com.example.actuator.controller.LoggerController: debug


# 톰캣 매트릭 활성화
server:
  tomcat:
    mbeanregistry:
      enabled: true
# 유용한 톰캣 메트릭
# tomcat.threads.config.max : 톰캣의 최대 스레드 수
# tomcat.threads.busy : 현재 바쁘게 사용중인 쓰레드 수

