management:
  endpoint:
    shutdown:
      enabled: true # shutdown 활성화
    health:
#      show-details: always
      show-components: always # up 인지만 확인
  endpoints:
    web:
      exposure:
        include: "*" # 전체 노출


# actuator 기능은 활성화, 노출 두가지가 다 되어있어야 사용할 수 있다.

