management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoint:
    shutdown:
      enabled: true # shutdown 활성화
    health:
#      show-details: always
      show-components: always # up 인지만 확인
  endpoints:
    web:
      exposure:
        include: "*" # 전체 노출

info:
  app:
    name: actuator-practice

logging:
  level:
    com.example.actuator.controller.LoggerController: debug
