# kubectl create secret generic db-password --from-literal="password=12"
# kubectl get secret db-password -o yaml
apiVersion: v1
data:
  password: MTI=
kind: Secret
metadata:
  creationTimestamp: "2024-05-19T08:39:40Z"
  name: db-password
  namespace: default
  resourceVersion: "306960"
  uid: 50822948-60d6-46fe-934e-e4b21c678f45
type: Opaque
