SET FOREIGN_KEY_CHECKS = 0;

truncate BATCH_JOB_EXECUTION;
truncate BATCH_JOB_EXECUTION_CONTEXT;
truncate BATCH_JOB_EXECUTION_PARAMS;
-- truncate BATCH_JOB_EXECUTION_SEQ;
truncate BATCH_JOB_INSTANCE;
-- truncate BATCH_JOB_SEQ;
truncate BATCH_STEP_EXECUTION;
truncate BATCH_STEP_EXECUTION_CONTEXT;
-- truncate BATCH_STEP_EXECUTION_SEQ;

SET FOREIGN_KEY_CHECKS = 1;
