spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3336/cache
    username: root
    password: 12
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  cache:
    jcache:
      config: classpath:ehcache.xml
  redis:
    host: localhost
    port: 6379

management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  server:
    port: 8181
  endpoint:
    health:
      #      show-details: always
      show-components: always # up 인지만 확인
  endpoints:
    web:
      exposure:
        include: "*" # 전체 노출
